remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  
# Exclude these files from your production _site
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
 
github: [metadata]

title: INI ML Reading Group
description: The INI ML Reading Group is the machine learning reading group at the INI at RUB.
show_downloads: false
repository: anandtrex/INI-ML-Reading-Group

